// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_loadingBar;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label11;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_PanelGear;
extern lv_obj_t * ui_LabeltextGear;
extern lv_obj_t * ui_LabelGear;
extern lv_obj_t * ui_PanelRPM;
extern lv_obj_t * ui_LabeltextRPM;
extern lv_obj_t * ui_LabelRPM;
extern lv_obj_t * ui_PanelSpeed;
extern lv_obj_t * ui_LabeltextSpeed;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_PanelGForce;
extern lv_obj_t * ui_LabeltextGForce;
extern lv_obj_t * ui_LabelGForce;
extern lv_obj_t * ui_LabelTPS;
extern lv_obj_t * ui_LabelBPS;
extern lv_obj_t * ui_BarRPM;
extern lv_obj_t * ui_LabelRev5K;
extern lv_obj_t * ui_LabelRev15;
extern lv_obj_t * ui_LabelRev10;
extern lv_obj_t * ui_BarTPS;
extern lv_obj_t * ui_BarBPS;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_227049602);    // assets\qmfs-logo-2.png

LV_FONT_DECLARE(ui_font_OD180);
LV_FONT_DECLARE(ui_font_OD26);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
