// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
extern lv_obj_t *ui_LoadingScreen;
extern lv_obj_t *ui_LoadingScreen_Image_Image1;
extern lv_obj_t *ui_LoadingScreen_Bar_loadingBar;
extern lv_obj_t *ui_LoadingScreen_Label_Label4;
extern lv_obj_t *ui_LoadingScreen_Label_Label11;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_MainScreen_Panel_PanelGear;
extern lv_obj_t *ui_MainScreen_Label_LabeltextGear;
extern lv_obj_t *ui_MainScreen_Label_LabelGear;
extern lv_obj_t *ui_MainScreen_Panel_PanelRPM;
extern lv_obj_t *ui_MainScreen_Label_LabeltextRPM;
extern lv_obj_t *ui_MainScreen_Label_LabelRPM;
extern lv_obj_t *ui_MainScreen_Panel_PanelSpeed;
extern lv_obj_t *ui_MainScreen_Label_LabeltextSpeed;
extern lv_obj_t *ui_MainScreen_Label_LabelSpeed;
extern lv_obj_t *ui_MainScreen_Panel_PanelGForce;
extern lv_obj_t *ui_MainScreen_Label_LabeltextGForce;
extern lv_obj_t *ui_MainScreen_Label_LabelGForce;
extern lv_obj_t *ui_MainScreen_Label_LabelTPS;
extern lv_obj_t *ui_MainScreen_Label_LabelBPS;
extern lv_obj_t *ui_MainScreen_Bar_BarRPM;
extern lv_obj_t *ui_MainScreen_Label_LabelRevPos1;
extern lv_obj_t *ui_MainScreen_Label_LabelRevPos2;
extern lv_obj_t *ui_MainScreen_Label_LabelRevPos3;
extern lv_obj_t *ui_MainScreen_Label_LabelRevPos4;
extern lv_obj_t *ui_MainScreen_Bar_BarTPS;
extern lv_obj_t *ui_MainScreen_Bar_BarBPS;
extern lv_obj_t *ui_MainScreen_Label_LabelBattV;
extern lv_obj_t *ui_MainScreen_Label_LabelGPSTrack;
extern lv_obj_t *ui_MainScreen_Label_LabelWaterTemp;
extern lv_obj_t *ui_MainScreen_Label_LabelOilTemp;
extern lv_obj_t *ui_MainScreen_Label_LabelTime;
extern lv_obj_t *ui_MainScreen_Label_LabelSDCardMounted;
// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_SettingScreen_Slider_SliderDisplayBrightness;
extern lv_obj_t *ui_SettingScreen_Label_LabelDisplayBrightness;
extern lv_obj_t *ui_SettingScreen_Label_LabelSetting;
extern lv_obj_t *ui_SettingScreen_Slider_SliderLEDBrightness;
extern lv_obj_t *ui_SettingScreen_Label_LabelLEDBrightness;
extern lv_obj_t *ui_SettingScreen_Switch_SwitchDemo;
extern lv_obj_t *ui_SettingScreen_Label_LabelDemo;
extern lv_obj_t *ui_SettingScreen_Label_LabelRecording;
void ui_event_SettingScreen_Button_ButtonsSettingReturn( lv_event_t * e);
extern lv_obj_t *ui_SettingScreen_Button_ButtonsSettingReturn;
extern lv_obj_t *ui_SettingScreen_Switch_SwitchRecord;
extern lv_obj_t *ui_SettingScreen_Button_ButtonBLEDisconnect;
extern lv_obj_t *ui_SettingScreen_Label_LabelRecordingStorage;
extern lv_obj_t *ui_SettingScreen_Button_ButtonRestart;
extern lv_obj_t *ui_SettingScreen_Label_LabelBLEDisconnect;
// SCREEN: ui_TeamScreen
void ui_TeamScreen_screen_init(void);
void ui_event_TeamScreen( lv_event_t * e);
extern lv_obj_t *ui_TeamScreen;
extern lv_obj_t *ui_TeamScreen_Image_Image2;
extern lv_obj_t *ui_TeamScreen_Image_Image3;
extern lv_obj_t *ui_TeamScreen_Label_LabelScanMe;
extern lv_obj_t *ui_TeamScreen_Label_LabelAd;
extern lv_obj_t *ui_TeamScreen_Image_ImageLinkedIn;
extern lv_obj_t *ui_TeamScreen_Image_ImageInsta;
extern lv_obj_t *ui_TeamScreen_Image_ImageTikTok;
extern lv_obj_t *ui_TeamScreen_Image_ImageYoutube;
// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
extern lv_obj_t *ui_InfoScreen;
extern lv_obj_t *ui_InfoScreen_Label_LabelFirmwareInfo;
extern lv_obj_t *ui_InfoScreen_Image_QRcodeGithub;
extern lv_obj_t *ui_InfoScreen_Label_LabelElectronicTeam;
extern lv_obj_t *ui_InfoScreen_Label_LabelGithub;
void ui_event_InfoScreen_Button_ButtonsInfoReturn( lv_event_t * e);
extern lv_obj_t *ui_InfoScreen_Button_ButtonsInfoReturn;
extern lv_obj_t *ui_InfoScreen_Label_LabelGPSInfo;
extern lv_obj_t *ui_InfoScreen_Panel_PanelGPSInfo;
extern lv_obj_t *ui_InfoScreen_Label_LabelBluetoothRSSI;
extern lv_obj_t *ui_InfoScreen_Label_LabelSpeedAcc;
extern lv_obj_t *ui_InfoScreen_Label_LabelGPSAcc;
extern lv_obj_t *ui_InfoScreen_Label_LabelDataRate;
extern lv_obj_t *ui_InfoScreen_Label_LabelSetting2;
extern lv_obj_t *ui_Startevents____initial_actions0;

LV_IMG_DECLARE( ui_img_1525559409);   // assets/qmfs-logo-2.png
LV_IMG_DECLARE( ui_img_880103820);   // assets/noun-return.png
LV_IMG_DECLARE( ui_img_1930579982);   // assets/restart-icon.png
LV_IMG_DECLARE( ui_img_166935938);   // assets/qr-code-qmfs.png
LV_IMG_DECLARE( ui_img_1828040333);   // assets/linkedin-logo.png
LV_IMG_DECLARE( ui_img_340328804);   // assets/insta-logo.png
LV_IMG_DECLARE( ui_img_111512867);   // assets/tiktok-logo.png
LV_IMG_DECLARE( ui_img_2128159454);   // assets/youtube-logo.png
LV_IMG_DECLARE( ui_img_786562192);   // assets/qr-code-github.png
LV_IMG_DECLARE( ui_img_488183857);   // assets/power-button.png


LV_FONT_DECLARE( ui_font_OD180);
LV_FONT_DECLARE( ui_font_OD250);
LV_FONT_DECLARE( ui_font_OD26);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
