// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_InfoScreen_screen_init(void)
{
ui_InfoScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_InfoScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InfoScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelFirmwareInfo = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Label_LabelFirmwareInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelFirmwareInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelFirmwareInfo, -98 );
lv_obj_set_y( ui_InfoScreen_Label_LabelFirmwareInfo, 76 );
lv_obj_set_align( ui_InfoScreen_Label_LabelFirmwareInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelFirmwareInfo,"Firmware Version: 1.0");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelFirmwareInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelFirmwareInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelFirmwareInfo, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Image_QRcodeGithub = lv_img_create(ui_InfoScreen);
lv_img_set_src(ui_InfoScreen_Image_QRcodeGithub, &ui_img_786562192);
lv_obj_set_width( ui_InfoScreen_Image_QRcodeGithub, LV_SIZE_CONTENT);  /// 259
lv_obj_set_height( ui_InfoScreen_Image_QRcodeGithub, LV_SIZE_CONTENT);   /// 259
lv_obj_set_x( ui_InfoScreen_Image_QRcodeGithub, 140 );
lv_obj_set_y( ui_InfoScreen_Image_QRcodeGithub, 21 );
lv_obj_set_align( ui_InfoScreen_Image_QRcodeGithub, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoScreen_Image_QRcodeGithub, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_InfoScreen_Image_QRcodeGithub, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_InfoScreen_Image_QRcodeGithub,120);

ui_InfoScreen_Label_LabelElectronicTeam = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Label_LabelElectronicTeam, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelElectronicTeam, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelElectronicTeam, -6 );
lv_obj_set_y( ui_InfoScreen_Label_LabelElectronicTeam, 136 );
lv_obj_set_align( ui_InfoScreen_Label_LabelElectronicTeam, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelElectronicTeam,"Designed by Electronics Team");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelElectronicTeam, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelElectronicTeam, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelElectronicTeam, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelGithub = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Label_LabelGithub, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelGithub, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelGithub, 139 );
lv_obj_set_y( ui_InfoScreen_Label_LabelGithub, -51 );
lv_obj_set_align( ui_InfoScreen_Label_LabelGithub, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelGithub,"GitHub Page");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelGithub, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelGithub, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelGithub, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Button_ButtonsInfoReturn = lv_btn_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Button_ButtonsInfoReturn, 61);
lv_obj_set_height( ui_InfoScreen_Button_ButtonsInfoReturn, 50);
lv_obj_set_x( ui_InfoScreen_Button_ButtonsInfoReturn, 188 );
lv_obj_set_y( ui_InfoScreen_Button_ButtonsInfoReturn, -125 );
lv_obj_set_align( ui_InfoScreen_Button_ButtonsInfoReturn, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_InfoScreen_Button_ButtonsInfoReturn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoScreen_Button_ButtonsInfoReturn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_InfoScreen_Button_ButtonsInfoReturn, &ui_img_880103820, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_color(ui_InfoScreen_Button_ButtonsInfoReturn, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Button_ButtonsInfoReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Button_ButtonsInfoReturn, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelGPSInfo = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Label_LabelGPSInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelGPSInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelGPSInfo, -131 );
lv_obj_set_y( ui_InfoScreen_Label_LabelGPSInfo, -81 );
lv_obj_set_align( ui_InfoScreen_Label_LabelGPSInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelGPSInfo,"GPS Module:");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelGPSInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelGPSInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelGPSInfo, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Panel_PanelGPSInfo = lv_obj_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Panel_PanelGPSInfo, 243);
lv_obj_set_height( ui_InfoScreen_Panel_PanelGPSInfo, 117);
lv_obj_set_x( ui_InfoScreen_Panel_PanelGPSInfo, -82 );
lv_obj_set_y( ui_InfoScreen_Panel_PanelGPSInfo, -4 );
lv_obj_set_align( ui_InfoScreen_Panel_PanelGPSInfo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_InfoScreen_Panel_PanelGPSInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InfoScreen_Panel_PanelGPSInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InfoScreen_Panel_PanelGPSInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoScreen_Panel_PanelGPSInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InfoScreen_Panel_PanelGPSInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InfoScreen_Panel_PanelGPSInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_InfoScreen_Panel_PanelGPSInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_InfoScreen_Panel_PanelGPSInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelBluetoothRSSI = lv_label_create(ui_InfoScreen_Panel_PanelGPSInfo);
lv_obj_set_width( ui_InfoScreen_Label_LabelBluetoothRSSI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelBluetoothRSSI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelBluetoothRSSI, -2 );
lv_obj_set_y( ui_InfoScreen_Label_LabelBluetoothRSSI, -46 );
lv_obj_set_align( ui_InfoScreen_Label_LabelBluetoothRSSI, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelBluetoothRSSI,"Bluetooth RSSI: -40dB");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelBluetoothRSSI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelBluetoothRSSI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelBluetoothRSSI, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelSpeedAcc = lv_label_create(ui_InfoScreen_Panel_PanelGPSInfo);
lv_obj_set_width( ui_InfoScreen_Label_LabelSpeedAcc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelSpeedAcc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelSpeedAcc, 12 );
lv_obj_set_y( ui_InfoScreen_Label_LabelSpeedAcc, -21 );
lv_obj_set_align( ui_InfoScreen_Label_LabelSpeedAcc, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelSpeedAcc,"Speed Accuracy: 0.2 mph");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelSpeedAcc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelSpeedAcc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelSpeedAcc, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelGPSAcc = lv_label_create(ui_InfoScreen_Panel_PanelGPSInfo);
lv_obj_set_width( ui_InfoScreen_Label_LabelGPSAcc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelGPSAcc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelGPSAcc, -5 );
lv_obj_set_y( ui_InfoScreen_Label_LabelGPSAcc, 8 );
lv_obj_set_align( ui_InfoScreen_Label_LabelGPSAcc, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelGPSAcc,"GPS Accuracy: 0.20m");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelGPSAcc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelGPSAcc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelGPSAcc, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelDataRate = lv_label_create(ui_InfoScreen_Panel_PanelGPSInfo);
lv_obj_set_width( ui_InfoScreen_Label_LabelDataRate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelDataRate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelDataRate, -9 );
lv_obj_set_y( ui_InfoScreen_Label_LabelDataRate, 34 );
lv_obj_set_align( ui_InfoScreen_Label_LabelDataRate, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelDataRate,"GPS Data Rate: 25Hz");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelDataRate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelDataRate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelDataRate, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreen_Label_LabelSetting2 = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoScreen_Label_LabelSetting2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoScreen_Label_LabelSetting2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoScreen_Label_LabelSetting2, 0 );
lv_obj_set_y( ui_InfoScreen_Label_LabelSetting2, -137 );
lv_obj_set_align( ui_InfoScreen_Label_LabelSetting2, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoScreen_Label_LabelSetting2,"INFO");
lv_obj_set_style_text_color(ui_InfoScreen_Label_LabelSetting2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_InfoScreen_Label_LabelSetting2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoScreen_Label_LabelSetting2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_InfoScreen_Button_ButtonsInfoReturn, ui_event_InfoScreen_Button_ButtonsInfoReturn, LV_EVENT_ALL, NULL);

}
