// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Panel_PanelGear = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Panel_PanelGear, 160);
lv_obj_set_height( ui_MainScreen_Panel_PanelGear, 223);
lv_obj_set_x( ui_MainScreen_Panel_PanelGear, 5 );
lv_obj_set_y( ui_MainScreen_Panel_PanelGear, 24 );
lv_obj_set_align( ui_MainScreen_Panel_PanelGear, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainScreen_Panel_PanelGear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainScreen_Panel_PanelGear, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Panel_PanelGear, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Panel_PanelGear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Panel_PanelGear, lv_color_hex(0xC3C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Panel_PanelGear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainScreen_Panel_PanelGear, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabeltextGear = lv_label_create(ui_MainScreen_Panel_PanelGear);
lv_obj_set_width( ui_MainScreen_Label_LabeltextGear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabeltextGear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabeltextGear, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabeltextGear, 94 );
lv_obj_set_align( ui_MainScreen_Label_LabeltextGear, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabeltextGear,"GEAR");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabeltextGear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabeltextGear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabeltextGear, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelGear = lv_label_create(ui_MainScreen_Panel_PanelGear);
lv_obj_set_width( ui_MainScreen_Label_LabelGear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelGear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelGear, 6 );
lv_obj_set_y( ui_MainScreen_Label_LabelGear, -38 );
lv_obj_set_align( ui_MainScreen_Label_LabelGear, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelGear,"2");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelGear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelGear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelGear, &ui_font_OD250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Panel_PanelRPM = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Panel_PanelRPM, 130);
lv_obj_set_height( ui_MainScreen_Panel_PanelRPM, 70);
lv_obj_set_x( ui_MainScreen_Panel_PanelRPM, -163 );
lv_obj_set_y( ui_MainScreen_Panel_PanelRPM, -50 );
lv_obj_set_align( ui_MainScreen_Panel_PanelRPM, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainScreen_Panel_PanelRPM, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainScreen_Panel_PanelRPM, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Panel_PanelRPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Panel_PanelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Panel_PanelRPM, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Panel_PanelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabeltextRPM = lv_label_create(ui_MainScreen_Panel_PanelRPM);
lv_obj_set_width( ui_MainScreen_Label_LabeltextRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabeltextRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabeltextRPM, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabeltextRPM, 20 );
lv_obj_set_align( ui_MainScreen_Label_LabeltextRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabeltextRPM,"RPM");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabeltextRPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabeltextRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabeltextRPM, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelRPM = lv_label_create(ui_MainScreen_Panel_PanelRPM);
lv_obj_set_width( ui_MainScreen_Label_LabelRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelRPM, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabelRPM, -10 );
lv_obj_set_align( ui_MainScreen_Label_LabelRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelRPM,"3000");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelRPM, lv_color_hex(0xD37D06), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelRPM, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Panel_PanelSpeed = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Panel_PanelSpeed, 130);
lv_obj_set_height( ui_MainScreen_Panel_PanelSpeed, 67);
lv_obj_set_x( ui_MainScreen_Panel_PanelSpeed, -163 );
lv_obj_set_y( ui_MainScreen_Panel_PanelSpeed, 29 );
lv_obj_set_align( ui_MainScreen_Panel_PanelSpeed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainScreen_Panel_PanelSpeed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainScreen_Panel_PanelSpeed, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Panel_PanelSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Panel_PanelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Panel_PanelSpeed, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Panel_PanelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabeltextSpeed = lv_label_create(ui_MainScreen_Panel_PanelSpeed);
lv_obj_set_width( ui_MainScreen_Label_LabeltextSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabeltextSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabeltextSpeed, -1 );
lv_obj_set_y( ui_MainScreen_Label_LabeltextSpeed, 23 );
lv_obj_set_align( ui_MainScreen_Label_LabeltextSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabeltextSpeed,"SPEED");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabeltextSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabeltextSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabeltextSpeed, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelSpeed = lv_label_create(ui_MainScreen_Panel_PanelSpeed);
lv_obj_set_width( ui_MainScreen_Label_LabelSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelSpeed, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabelSpeed, -10 );
lv_obj_set_align( ui_MainScreen_Label_LabelSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelSpeed,"25");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelSpeed, lv_color_hex(0xD37D06), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelSpeed, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Panel_PanelGForce = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Panel_PanelGForce, 122);
lv_obj_set_height( ui_MainScreen_Panel_PanelGForce, 60);
lv_obj_set_x( ui_MainScreen_Panel_PanelGForce, 166 );
lv_obj_set_y( ui_MainScreen_Panel_PanelGForce, 62 );
lv_obj_set_align( ui_MainScreen_Panel_PanelGForce, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_MainScreen_Panel_PanelGForce, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainScreen_Panel_PanelGForce, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Panel_PanelGForce, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Panel_PanelGForce, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Panel_PanelGForce, lv_color_hex(0x8B8B8B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Panel_PanelGForce, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabeltextGForce = lv_label_create(ui_MainScreen_Panel_PanelGForce);
lv_obj_set_width( ui_MainScreen_Label_LabeltextGForce, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabeltextGForce, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabeltextGForce, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabeltextGForce, 15 );
lv_obj_set_align( ui_MainScreen_Label_LabeltextGForce, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabeltextGForce,"G-FORCE");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabeltextGForce, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabeltextGForce, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabeltextGForce, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelGForce = lv_label_create(ui_MainScreen_Panel_PanelGForce);
lv_obj_set_width( ui_MainScreen_Label_LabelGForce, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelGForce, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelGForce, 0 );
lv_obj_set_y( ui_MainScreen_Label_LabelGForce, -10 );
lv_obj_set_align( ui_MainScreen_Label_LabelGForce, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelGForce,"1.0");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelGForce, lv_color_hex(0xD37D06), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelGForce, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelGForce, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelTPS = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelTPS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelTPS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelTPS, 131 );
lv_obj_set_y( ui_MainScreen_Label_LabelTPS, 18 );
lv_obj_set_align( ui_MainScreen_Label_LabelTPS, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelTPS,"TPS");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelTPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelTPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelTPS, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelBPS = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelBPS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelBPS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelBPS, 200 );
lv_obj_set_y( ui_MainScreen_Label_LabelBPS, 18 );
lv_obj_set_align( ui_MainScreen_Label_LabelBPS, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelBPS,"BPS");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelBPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelBPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelBPS, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Bar_BarRPM = lv_bar_create(ui_MainScreen);
lv_bar_set_value(ui_MainScreen_Bar_BarRPM,5,LV_ANIM_OFF);
lv_bar_set_start_value(ui_MainScreen_Bar_BarRPM, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_MainScreen_Bar_BarRPM, 460);
lv_obj_set_height( ui_MainScreen_Bar_BarRPM, 45);
lv_obj_set_x( ui_MainScreen_Bar_BarRPM, 0 );
lv_obj_set_y( ui_MainScreen_Bar_BarRPM, -130 );
lv_obj_set_align( ui_MainScreen_Bar_BarRPM, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_MainScreen_Bar_BarRPM, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarRPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarRPM, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Bar_BarRPM, lv_color_hex(0xC3C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Bar_BarRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainScreen_Bar_BarRPM, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_MainScreen_Bar_BarRPM, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarRPM, lv_color_hex(0xD37D06), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarRPM, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelRevPos1 = lv_label_create(ui_MainScreen_Bar_BarRPM);
lv_obj_set_width( ui_MainScreen_Label_LabelRevPos1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelRevPos1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelRevPos1, -130 );
lv_obj_set_y( ui_MainScreen_Label_LabelRevPos1, 0 );
lv_obj_set_align( ui_MainScreen_Label_LabelRevPos1, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelRevPos1,"3K |");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelRevPos1, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelRevPos1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelRevPos1, &ui_font_OD26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelRevPos2 = lv_label_create(ui_MainScreen_Bar_BarRPM);
lv_obj_set_width( ui_MainScreen_Label_LabelRevPos2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelRevPos2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelRevPos2, -15 );
lv_obj_set_y( ui_MainScreen_Label_LabelRevPos2, 0 );
lv_obj_set_align( ui_MainScreen_Label_LabelRevPos2, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelRevPos2,"6K |");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelRevPos2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelRevPos2, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelRevPos2, &ui_font_OD26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelRevPos3 = lv_label_create(ui_MainScreen_Bar_BarRPM);
lv_obj_set_width( ui_MainScreen_Label_LabelRevPos3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelRevPos3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelRevPos3, 100 );
lv_obj_set_y( ui_MainScreen_Label_LabelRevPos3, 0 );
lv_obj_set_align( ui_MainScreen_Label_LabelRevPos3, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelRevPos3,"9K |");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelRevPos3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelRevPos3, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelRevPos3, &ui_font_OD26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelRevPos4 = lv_label_create(ui_MainScreen_Bar_BarRPM);
lv_obj_set_width( ui_MainScreen_Label_LabelRevPos4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelRevPos4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelRevPos4, 205 );
lv_obj_set_y( ui_MainScreen_Label_LabelRevPos4, 0 );
lv_obj_set_align( ui_MainScreen_Label_LabelRevPos4, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelRevPos4,"12K |");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelRevPos4, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelRevPos4, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelRevPos4, &ui_font_OD26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Bar_BarTPS = lv_bar_create(ui_MainScreen);
lv_bar_set_value(ui_MainScreen_Bar_BarTPS,60,LV_ANIM_OFF);
lv_bar_set_start_value(ui_MainScreen_Bar_BarTPS, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_MainScreen_Bar_BarTPS, 45);
lv_obj_set_height( ui_MainScreen_Bar_BarTPS, 90);
lv_obj_set_x( ui_MainScreen_Bar_BarTPS, 130 );
lv_obj_set_y( ui_MainScreen_Bar_BarTPS, -40 );
lv_obj_set_align( ui_MainScreen_Bar_BarTPS, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_MainScreen_Bar_BarTPS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarTPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarTPS, 60, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_MainScreen_Bar_BarTPS, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarTPS, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarTPS, 200, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_MainScreen_Bar_BarBPS = lv_bar_create(ui_MainScreen);
lv_bar_set_value(ui_MainScreen_Bar_BarBPS,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_MainScreen_Bar_BarBPS, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_MainScreen_Bar_BarBPS, 45);
lv_obj_set_height( ui_MainScreen_Bar_BarBPS, 90);
lv_obj_set_x( ui_MainScreen_Bar_BarBPS, 200 );
lv_obj_set_y( ui_MainScreen_Bar_BarBPS, -40 );
lv_obj_set_align( ui_MainScreen_Bar_BarBPS, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_MainScreen_Bar_BarBPS, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarBPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarBPS, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainScreen_Bar_BarBPS, lv_color_hex(0xC3C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainScreen_Bar_BarBPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_MainScreen_Bar_BarBPS, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainScreen_Bar_BarBPS, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen_Bar_BarBPS, 200, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelBattV = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelBattV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelBattV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelBattV, -160 );
lv_obj_set_y( ui_MainScreen_Label_LabelBattV, 116 );
lv_obj_set_align( ui_MainScreen_Label_LabelBattV, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelBattV,"Batt: 13.4V");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelBattV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelBattV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelBattV, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelGPSTrack = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelGPSTrack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelGPSTrack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelGPSTrack, 6 );
lv_obj_set_y( ui_MainScreen_Label_LabelGPSTrack, -97 );
lv_obj_set_align( ui_MainScreen_Label_LabelGPSTrack, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelGPSTrack,"GPS Fix: 4");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelGPSTrack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelGPSTrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelGPSTrack, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelWaterTemp = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelWaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelWaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelWaterTemp, -160 );
lv_obj_set_y( ui_MainScreen_Label_LabelWaterTemp, 89 );
lv_obj_set_align( ui_MainScreen_Label_LabelWaterTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelWaterTemp,"Water: 97 C");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelWaterTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelWaterTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelWaterTemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelOilTemp = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelOilTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelOilTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelOilTemp, -160 );
lv_obj_set_y( ui_MainScreen_Label_LabelOilTemp, 143 );
lv_obj_set_align( ui_MainScreen_Label_LabelOilTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelOilTemp,"Oil: 122 C");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelOilTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelOilTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelOilTemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelSDCardMounted = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelSDCardMounted, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelSDCardMounted, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelSDCardMounted, 160 );
lv_obj_set_y( ui_MainScreen_Label_LabelSDCardMounted, 116 );
lv_obj_set_align( ui_MainScreen_Label_LabelSDCardMounted, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelSDCardMounted,"SD: Mounted");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelSDCardMounted, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelSDCardMounted, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelSDCardMounted, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainScreen_Label_LabelTime = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_MainScreen_Label_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MainScreen_Label_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MainScreen_Label_LabelTime, 4 );
lv_obj_set_y( ui_MainScreen_Label_LabelTime, 148 );
lv_obj_set_align( ui_MainScreen_Label_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainScreen_Label_LabelTime,"Time: 12:00");
lv_obj_set_style_text_color(ui_MainScreen_Label_LabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainScreen_Label_LabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainScreen_Label_LabelTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
