// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Slider_SliderDisplayBrightness = lv_slider_create(ui_SettingScreen);
    lv_slider_set_value(ui_SettingScreen_Slider_SliderDisplayBrightness, 60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SettingScreen_Slider_SliderDisplayBrightness) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_SettingScreen_Slider_SliderDisplayBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SettingScreen_Slider_SliderDisplayBrightness, 400);
    lv_obj_set_height(ui_SettingScreen_Slider_SliderDisplayBrightness, 10);
    lv_obj_set_x(ui_SettingScreen_Slider_SliderDisplayBrightness, 2);
    lv_obj_set_y(ui_SettingScreen_Slider_SliderDisplayBrightness, -66);
    lv_obj_set_align(ui_SettingScreen_Slider_SliderDisplayBrightness, LV_ALIGN_CENTER);


    ui_SettingScreen_Label_LabelDisplayBrightness = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelDisplayBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelDisplayBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelDisplayBrightness, -101);
    lv_obj_set_y(ui_SettingScreen_Label_LabelDisplayBrightness, -91);
    lv_obj_set_align(ui_SettingScreen_Label_LabelDisplayBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelDisplayBrightness, "Display Brightness:");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelDisplayBrightness, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelDisplayBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelDisplayBrightness, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Label_LabelSetting = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelSetting, -1);
    lv_obj_set_y(ui_SettingScreen_Label_LabelSetting, -136);
    lv_obj_set_align(ui_SettingScreen_Label_LabelSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelSetting, "SETTINGS");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelSetting, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelSetting, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Slider_SliderLEDBrightness = lv_slider_create(ui_SettingScreen);
    lv_slider_set_value(ui_SettingScreen_Slider_SliderLEDBrightness, 40, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SettingScreen_Slider_SliderLEDBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SettingScreen_Slider_SliderLEDBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SettingScreen_Slider_SliderLEDBrightness, 400);
    lv_obj_set_height(ui_SettingScreen_Slider_SliderLEDBrightness, 10);
    lv_obj_set_x(ui_SettingScreen_Slider_SliderLEDBrightness, 2);
    lv_obj_set_y(ui_SettingScreen_Slider_SliderLEDBrightness, -16);
    lv_obj_set_align(ui_SettingScreen_Slider_SliderLEDBrightness, LV_ALIGN_CENTER);


    ui_SettingScreen_Label_LabelLEDBrightness = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelLEDBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelLEDBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelLEDBrightness, -114);
    lv_obj_set_y(ui_SettingScreen_Label_LabelLEDBrightness, -41);
    lv_obj_set_align(ui_SettingScreen_Label_LabelLEDBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelLEDBrightness, "LED Brightness:");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelLEDBrightness, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelLEDBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelLEDBrightness, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Switch_SwitchDemo = lv_switch_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Switch_SwitchDemo, 60);
    lv_obj_set_height(ui_SettingScreen_Switch_SwitchDemo, 35);
    lv_obj_set_x(ui_SettingScreen_Switch_SwitchDemo, -25);
    lv_obj_set_y(ui_SettingScreen_Switch_SwitchDemo, 36);
    lv_obj_set_align(ui_SettingScreen_Switch_SwitchDemo, LV_ALIGN_CENTER);


    ui_SettingScreen_Label_LabelDemo = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelDemo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelDemo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelDemo, -130);
    lv_obj_set_y(ui_SettingScreen_Label_LabelDemo, 38);
    lv_obj_set_align(ui_SettingScreen_Label_LabelDemo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelDemo, "Demo mode:");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelDemo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelDemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelDemo, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Label_LabelRecording = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelRecording, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelRecording, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelRecording, -130);
    lv_obj_set_y(ui_SettingScreen_Label_LabelRecording, 102);
    lv_obj_set_align(ui_SettingScreen_Label_LabelRecording, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelRecording, "Record Data:");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelRecording, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelRecording, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelRecording, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Button_ButtonsSettingReturn = lv_btn_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Button_ButtonsSettingReturn, 61);
    lv_obj_set_height(ui_SettingScreen_Button_ButtonsSettingReturn, 50);
    lv_obj_set_x(ui_SettingScreen_Button_ButtonsSettingReturn, 188);
    lv_obj_set_y(ui_SettingScreen_Button_ButtonsSettingReturn, -125);
    lv_obj_set_align(ui_SettingScreen_Button_ButtonsSettingReturn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingScreen_Button_ButtonsSettingReturn, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen_Button_ButtonsSettingReturn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingScreen_Button_ButtonsSettingReturn, &ui_img_880103820,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_SettingScreen_Button_ButtonsSettingReturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SettingScreen_Button_ButtonsSettingReturn, lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Button_ButtonsSettingReturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Button_ButtonsSettingReturn, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Switch_SwitchRecord = lv_switch_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Switch_SwitchRecord, 60);
    lv_obj_set_height(ui_SettingScreen_Switch_SwitchRecord, 35);
    lv_obj_set_x(ui_SettingScreen_Switch_SwitchRecord, -25);
    lv_obj_set_y(ui_SettingScreen_Switch_SwitchRecord, 102);
    lv_obj_set_align(ui_SettingScreen_Switch_SwitchRecord, LV_ALIGN_CENTER);


    ui_SettingScreen_Button_ButtonBLEDisconnect = lv_btn_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Button_ButtonBLEDisconnect, 132);
    lv_obj_set_height(ui_SettingScreen_Button_ButtonBLEDisconnect, 50);
    lv_obj_set_x(ui_SettingScreen_Button_ButtonBLEDisconnect, 143);
    lv_obj_set_y(ui_SettingScreen_Button_ButtonBLEDisconnect, 37);
    lv_obj_set_align(ui_SettingScreen_Button_ButtonBLEDisconnect, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingScreen_Button_ButtonBLEDisconnect, lv_color_hex(0xBBBBBB),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen_Button_ButtonBLEDisconnect, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingScreen_Button_ButtonBLEDisconnect, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingScreen_Button_ButtonBLEDisconnect, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingScreen_Button_ButtonBLEDisconnect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Label_LabelRecordingStorage = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelRecordingStorage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelRecordingStorage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelRecordingStorage, -93);
    lv_obj_set_y(ui_SettingScreen_Label_LabelRecordingStorage, 141);
    lv_obj_set_align(ui_SettingScreen_Label_LabelRecordingStorage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelRecordingStorage, "Storage Remaining: 99%");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelRecordingStorage, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelRecordingStorage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelRecordingStorage, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Button_ButtonRestart = lv_btn_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Button_ButtonRestart, 132);
    lv_obj_set_height(ui_SettingScreen_Button_ButtonRestart, 50);
    lv_obj_set_x(ui_SettingScreen_Button_ButtonRestart, 144);
    lv_obj_set_y(ui_SettingScreen_Button_ButtonRestart, 112);
    lv_obj_set_align(ui_SettingScreen_Button_ButtonRestart, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingScreen_Button_ButtonRestart, lv_color_hex(0xEB3B3B),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen_Button_ButtonRestart, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingScreen_Button_ButtonRestart, &ui_img_488183857, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingScreen_Button_ButtonRestart, lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingScreen_Button_ButtonRestart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingScreen_Button_ButtonRestart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Label_LabelBLEDisconnect = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_Label_LabelBLEDisconnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label_LabelBLEDisconnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingScreen_Label_LabelBLEDisconnect, 142);
    lv_obj_set_y(ui_SettingScreen_Label_LabelBLEDisconnect, 38);
    lv_obj_set_align(ui_SettingScreen_Label_LabelBLEDisconnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label_LabelBLEDisconnect, "BLUETOOTH\nDISCONNECT");
    lv_obj_set_style_text_color(ui_SettingScreen_Label_LabelBLEDisconnect, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingScreen_Label_LabelBLEDisconnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingScreen_Label_LabelBLEDisconnect, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingScreen_Button_ButtonsSettingReturn, ui_event_SettingScreen_Button_ButtonsSettingReturn,
                        LV_EVENT_ALL, NULL);

}
