// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_TeamScreen_screen_init(void)
{
ui_TeamScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TeamScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TeamScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TeamScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TeamScreen_Image_Image2 = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_Image2, &ui_img_166935938);
lv_obj_set_width( ui_TeamScreen_Image_Image2, LV_SIZE_CONTENT);  /// 180
lv_obj_set_height( ui_TeamScreen_Image_Image2, LV_SIZE_CONTENT);   /// 231
lv_obj_set_x( ui_TeamScreen_Image_Image2, 134 );
lv_obj_set_y( ui_TeamScreen_Image_Image2, 55 );
lv_obj_set_align( ui_TeamScreen_Image_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_Image2,130);

ui_TeamScreen_Image_Image3 = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_Image3, &ui_img_1525559409);
lv_obj_set_width( ui_TeamScreen_Image_Image3, LV_SIZE_CONTENT);  /// 319
lv_obj_set_height( ui_TeamScreen_Image_Image3, LV_SIZE_CONTENT);   /// 88
lv_obj_set_x( ui_TeamScreen_Image_Image3, 6 );
lv_obj_set_y( ui_TeamScreen_Image_Image3, -80 );
lv_obj_set_align( ui_TeamScreen_Image_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_Image3,350);

ui_TeamScreen_Label_LabelScanMe = lv_label_create(ui_TeamScreen);
lv_obj_set_width( ui_TeamScreen_Label_LabelScanMe, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TeamScreen_Label_LabelScanMe, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TeamScreen_Label_LabelScanMe, 134 );
lv_obj_set_y( ui_TeamScreen_Label_LabelScanMe, 129 );
lv_obj_set_align( ui_TeamScreen_Label_LabelScanMe, LV_ALIGN_CENTER );
lv_label_set_text(ui_TeamScreen_Label_LabelScanMe,"Scan Me");
lv_obj_set_style_text_color(ui_TeamScreen_Label_LabelScanMe, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TeamScreen_Label_LabelScanMe, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TeamScreen_Label_LabelScanMe, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TeamScreen_Label_LabelAd = lv_label_create(ui_TeamScreen);
lv_obj_set_width( ui_TeamScreen_Label_LabelAd, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TeamScreen_Label_LabelAd, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TeamScreen_Label_LabelAd, -87 );
lv_obj_set_y( ui_TeamScreen_Label_LabelAd, 93 );
lv_obj_set_align( ui_TeamScreen_Label_LabelAd, LV_ALIGN_CENTER );
lv_label_set_text(ui_TeamScreen_Label_LabelAd,"@qmformulastudent");
lv_obj_set_style_text_color(ui_TeamScreen_Label_LabelAd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TeamScreen_Label_LabelAd, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TeamScreen_Label_LabelAd, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TeamScreen_Image_ImageLinkedIn = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_ImageLinkedIn, &ui_img_1828040333);
lv_obj_set_width( ui_TeamScreen_Image_ImageLinkedIn, LV_SIZE_CONTENT);  /// 146
lv_obj_set_height( ui_TeamScreen_Image_ImageLinkedIn, LV_SIZE_CONTENT);   /// 144
lv_obj_set_x( ui_TeamScreen_Image_ImageLinkedIn, -180 );
lv_obj_set_y( ui_TeamScreen_Image_ImageLinkedIn, 40 );
lv_obj_set_align( ui_TeamScreen_Image_ImageLinkedIn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_ImageLinkedIn, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_ImageLinkedIn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_ImageLinkedIn,90);

ui_TeamScreen_Image_ImageInsta = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_ImageInsta, &ui_img_340328804);
lv_obj_set_width( ui_TeamScreen_Image_ImageInsta, LV_SIZE_CONTENT);  /// 147
lv_obj_set_height( ui_TeamScreen_Image_ImageInsta, LV_SIZE_CONTENT);   /// 143
lv_obj_set_x( ui_TeamScreen_Image_ImageInsta, -120 );
lv_obj_set_y( ui_TeamScreen_Image_ImageInsta, 40 );
lv_obj_set_align( ui_TeamScreen_Image_ImageInsta, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_ImageInsta, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_ImageInsta, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_ImageInsta,90);

ui_TeamScreen_Image_ImageTikTok = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_ImageTikTok, &ui_img_111512867);
lv_obj_set_width( ui_TeamScreen_Image_ImageTikTok, LV_SIZE_CONTENT);  /// 152
lv_obj_set_height( ui_TeamScreen_Image_ImageTikTok, LV_SIZE_CONTENT);   /// 144
lv_obj_set_x( ui_TeamScreen_Image_ImageTikTok, -55 );
lv_obj_set_y( ui_TeamScreen_Image_ImageTikTok, 40 );
lv_obj_set_align( ui_TeamScreen_Image_ImageTikTok, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_ImageTikTok, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_ImageTikTok, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_ImageTikTok,90);

ui_TeamScreen_Image_ImageYoutube = lv_img_create(ui_TeamScreen);
lv_img_set_src(ui_TeamScreen_Image_ImageYoutube, &ui_img_2128159454);
lv_obj_set_width( ui_TeamScreen_Image_ImageYoutube, LV_SIZE_CONTENT);  /// 145
lv_obj_set_height( ui_TeamScreen_Image_ImageYoutube, LV_SIZE_CONTENT);   /// 145
lv_obj_set_x( ui_TeamScreen_Image_ImageYoutube, 10 );
lv_obj_set_y( ui_TeamScreen_Image_ImageYoutube, 40 );
lv_obj_set_align( ui_TeamScreen_Image_ImageYoutube, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TeamScreen_Image_ImageYoutube, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TeamScreen_Image_ImageYoutube, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TeamScreen_Image_ImageYoutube,90);

lv_obj_add_event_cb(ui_TeamScreen, ui_event_TeamScreen, LV_EVENT_ALL, NULL);

}
