#define LGFX_USE_V1
#define SERIAL_BAUDRATE 115200

// PIN DEFINITIONS
#define RGB_PIN 	  4
#define BUZZER_PIN 	  5
#define CANBUS_CS_PIN 40
#define SDCS 		  41
#define SD_DETECT     46
#define SD_DETECT_GPIO GPIO_NUM_46

// SPI PIN DEFINITIONS
#define MISO 7
#define MOSI 15
#define SCLK 16

// LED DEFINITION
#define NUM_RPM_LEDS           10
#define LED_DEFAULT_BRIGHTNESS 20
#define MAX_RPM				   12000

// SCREEN DEFINITIONS
#define SCREEN_WIDTH 		   480
#define SCREEN_HEIGHT 		   320
#define SCREEN_COLOUR_DIVISOR  10
#define TFT_DEFAULT_BRIGHTNESS 100
#define DISPLAY_ROTATION       1

// CAN BUS DEFINITIONS
#define CANBUS_DATA_COUNT 				6
#define PID_ECU_RESPONSE 				0x7E8
#define PID_ENGINE_RPM 					0x0C
#define PID_THROTTLE 					0x11
#define PID_COOLANT_TEMP 				0x05
#define PID_ENGINE_OIL_TEMP 			0x5C
#define PID_TRANSMISSION_ACTUAL_GEAR 	0xA4
#define PID_CONTROL_MODULE_VOLTAGE 		0x42 // Battery voltage
// #define PID_INTAKE_TEMP 0x0F

// Delays
#define DISPLAY_INIT_DELAY      350
#define LOADING_SCREEN_DELAY    10
#define CANBUS_START_DELAY      1000
#define RESTART_DELAY           1000
#define UPSHIFT_BLINK_DELAY     200
#define LED_ANIMATION_DELAY     250
#define BUZZER_TONE_DELAY       100

// GPS Module Bluetooth UUID
#define BLE_UART_UUID "E400001-B5A3-F393-E0A9-E50E24DCCA9E"
#define BLE_TX_UUID "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"

#define GPS_SERIAL_FREQUENCY 8