#define LGFX_USE_V1

// PIN DEFS
#define RGB_PIN 4
#define BUZZER_PIN 5
#define CANBUS_CS_PIN 40
#define SDCS 41
#define SD_DETECT 46

// DEFS
#define NUM_RPM_LEDS 10
#define SCREEN_WIDTH 480
#define SCREEN_HEIGHT 320
#define TFT_DEFAULT_BRIGHTNESS 100
#define LED_DEFAULT_BRIGHTNESS 20

// CAN DEFS
#define CANBUS_DATA_COUNT 6
#define PID_ECU_RESPONSE 0x7E8
#define PID_ENGINE_RPM 0x0C
#define PID_THROTTLE 0x11
#define PID_COOLANT_TEMP 0x05
#define PID_ENGINE_OIL_TEMP 0x5C
#define PID_TRANSMISSION_ACTUAL_GEAR 0xA4
#define PID_CONTROL_MODULE_VOLTAGE 0x42 // Battery voltage
// #define PID_INTAKE_TEMP 0x0F